### ISSUE TITLE
Upgrade gems

### ISSUE THREAD

**Issue by JakobKohler** [Langschwanzpinguine/Bahnhofottos#31]
Upgrade gems to latest version

**Comment by nils-matthaei** [comment]
In commit f8c1d0e the following gems were updated:
- rails: 7.0.6 -> 7.1.3
- puma: 5.0 -> 6.4
- bcrypt: 3.1.7 -> 3.1.20
- image_processing: 1.2 -> 1.13

Trying to update the sqlite3 gem from 1.4 to 2.0 produces this error:

```
Puma caught this error: Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.4), already activated sqlite3-2.0.3-x86_64-linux-gnu. Make sure all dependencies are added to Gemfile. (LoadError)
/usr/share/rvm/rubies/ruby-3.1.4/lib/ruby/3.1.0/bundler/rubygems_integration.rb:280:in `block (2 levels) in replace_gem'
/usr/share/rvm/gems/ruby-3.1.4/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:14:in `<main>'
/usr/share/rvm/gems/ruby-3.1.4/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/share/rvm/gems/ruby-3.1.4/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/share/rvm/gems/ruby-3.1.4/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
/usr/share/rvm/gems/ruby-3.1.4/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/connection_handler.rb:333:in `resolve_pool_config'
/usr/share/rvm/gems/ruby-3.1.4/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/connection_handler.rb:134:in `establish_connection'
/usr/share/rvm/gems/ruby-3.1.4/gems/activerecord-7.1.3.4/lib/active_record/connection_handling.rb:53:in `establish_connection'
/usr/share/rvm/gems/ruby-3.1.4/gems/activerecord-7.1.3.4/lib/active_record/railtie.rb:304:in `block (2 levels) in <class:Railtie>'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:97:in `class_eval'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:97:in `block in execute_hook'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:78:in `block in run_load_hooks'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:77:in `each'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/lazy_load_hooks.rb:77:in `run_load_hooks'
/usr/share/rvm/gems/ruby-3.1.4/gems/activerecord-7.1.3.4/lib/active_record/base.rb:338:in `<module:ActiveRecord>'
/usr/share/rvm/gems/ruby-3.1.4/gems/activerecord-7.1.3.4/lib/active_record/base.rb:15:in `<main>'
/usr/share/rvm/gems/ruby-3.1.4/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/share/rvm/gems/ruby-3.1.4/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/share/rvm/gems/ruby-3.1.4/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
/usr/share/rvm/gems/ruby-3.1.4/gems/activerecord-7.1.3.4/lib/active_record/query_cache.rb:29:in `run'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/execution_wrapper.rb:29:in `before'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:202:in `block (2 levels) in halting'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:707:in `block (2 levels) in default_terminator'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:706:in `catch'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:706:in `block in default_terminator'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:203:in `block in halting'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:598:in `block in invoke_before'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:598:in `each'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:598:in `invoke_before'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:109:in `run_callbacks'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/execution_wrapper.rb:129:in `run'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/execution_wrapper.rb:125:in `run!'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/execution_wrapper.rb:78:in `block in run!'
<internal:kernel>:90:in `tap'
/usr/share/rvm/gems/ruby-3.1.4/gems/activesupport-7.1.3.4/lib/active_support/execution_wrapper.rb:75:in `run!'
/usr/share/rvm/gems/ruby-3.1.4/gems/actionpack-7.1.3.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
/usr/share/rvm/gems/ruby-3.1.4/gems/actionpack-7.1.3.4/lib/action_dispatch/middleware/static.rb:25:in `call'
/usr/share/rvm/gems/ruby-3.1.4/gems/rack-2.2.8/lib/rack/sendfile.rb:110:in `call'
/usr/share/rvm/gems/ruby-3.1.4/gems/actionpack-7.1.3.4/lib/action_dispatch/middleware/host_authorization.rb:141:in `call'
/usr/share/rvm/gems/ruby-3.1.4/gems/rack-cors-2.0.1/lib/rack/cors.rb:102:in `call'
/usr/share/rvm/gems/ruby-3.1.4/gems/railties-7.1.3.4/lib/rails/engine.rb:536:in `call'
/usr/share/rvm/gems/ruby-3.1.4/gems/puma-6.4.2/lib/puma/configuration.rb:272:in `call'
/usr/share/rvm/gems/ruby-3.1.4/gems/puma-6.4.2/lib/puma/request.rb:100:in `block in handle_request'
/usr/share/rvm/gems/ruby-3.1.4/gems/puma-6.4.2/lib/puma/thread_pool.rb:378:in `with_force_shutdown'
/usr/share/rvm/gems/ruby-3.1.4/gems/puma-6.4.2/lib/puma/request.rb:99:in `handle_request'
/usr/share/rvm/gems/ruby-3.1.4/gems/puma-6.4.2/lib/puma/server.rb:464:in `process_client'
/usr/share/rvm/gems/ruby-3.1.4/gems/puma-6.4.2/lib/puma/server.rb:245:in `block in run'
/usr/share/rvm/gems/ruby-3.1.4/gems/puma-6.4.2/lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```
